# SPDX-License-Identifier: GPL-3.0-or-later
"""Validate the forward-build param schemas without Blender.

Every kind in ``forward.BUILD_KINDS`` must produce a param dict carrying the
exact keys the exporters' schema (operators._PARAM_KINDS / step_export) reads,
and an exact (rms=0) FitResult with a human summary.

    python3 reverse_mesh/tests/test_forward_params.py
"""

import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import forward  # noqa: E402

# Mirrors operators._PARAM_KINDS for the forward-buildable kinds (operators.py
# imports bpy, so the expectation is duplicated here rather than imported).
EXPECTED_KEYS = {
    "BOX": {"center", "ax", "ay", "az", "hx", "hy", "hz"},
    "CYLINDER": {"base", "axis", "radius", "height"},
    "CONE": {"base", "axis", "radius1", "radius2", "height", "half_angle"},
    "SPHERE": {"center", "radius"},
    "TORUS": {"center", "axis", "major_radius", "minor_radius"},
    "EXTRUDE": {"base", "axis", "xdir", "height", "radius", "sides", "profile"},
    "REVOLVE": {"base", "axis", "height", "radius1", "radius2", "profile"},
}

DIMS = {
    "BOX": {"hx": 1.0, "hy": 2.0, "hz": 3.0},
    "CYLINDER": {"radius": 2.0, "height": 6.0},
    "CONE": {"radius1": 3.0, "radius2": 1.0, "height": 4.0},
    "SPHERE": {"radius": 2.5},
    "TORUS": {"major_radius": 4.0, "minor_radius": 1.0},
    "EXTRUDE": {"radius": 2.0, "height": 3.0, "sides": 8},
    "REVOLVE": {"radius1": 1.0, "radius2": 2.0, "height": 0.5},
}


def fail(msg):
    print(f"[FAIL] {msg}")
    sys.exit(1)


def main():
    if set(forward.BUILD_KINDS) != set(EXPECTED_KEYS):
        fail(f"BUILD_KINDS {forward.BUILD_KINDS} != expected {set(EXPECTED_KEYS)}")
    loc = (10.0, 20.0, 30.0)
    for kind in forward.BUILD_KINDS:
        params = forward.make_params(kind, DIMS[kind], loc)
        if set(params) != EXPECTED_KEYS[kind]:
            fail(f"{kind}: params keys {set(params)} != {EXPECTED_KEYS[kind]}")
        # Every PARAM_FIELDS entry must exist in the produced params.
        for key, _label in forward.PARAM_FIELDS[kind]:
            if key not in params:
                fail(f"{kind}: editable field '{key}' missing from params")
        result = forward.make_result(kind, params)
        if result.rms != 0.0 or result.max_error != 0.0:
            fail(f"{kind}: built primitive must be exact (rms=0)")
        if not result.summary:
            fail(f"{kind}: empty summary")
        print(f"[ok] {kind}: {result.summary}")

    # Cone: half_angle consistent with its radii, base offset to centre the body.
    p = forward.make_params("CONE", DIMS["CONE"], loc)
    want = math.atan(abs(1.0 - 3.0) / 4.0)
    if abs(p["half_angle"] - want) > 1e-12:
        fail(f"cone half_angle {p['half_angle']} != {want}")
    if abs(p["base"][2] - (30.0 - 2.0)) > 1e-12:
        fail(f"cone base z {p['base'][2]} not offset by -h/2")
    # Extrude: an 8-gon profile (one LINE row per side), centred on the drop,
    # regenerated by refresh_extrude_profile when the radius changes.
    p = forward.make_params("EXTRUDE", DIMS["EXTRUDE"], loc)
    if len(p["profile"]) != 8 or any(row[0] != 0.0 for row in p["profile"]):
        fail(f"extrude profile should be 8 LINE rows, got {p['profile']}")
    if abs(p["base"][2] - (30.0 - 1.5)) > 1e-12:
        fail(f"extrude base z {p['base'][2]} not offset by -h/2")
    r0 = math.hypot(p["profile"][0][1], p["profile"][0][2])
    if abs(r0 - 2.0) > 1e-12:
        fail(f"extrude profile circumradius {r0} != 2.0")
    p2 = dict(p, kind="EXTRUDE", radius=5.0)
    if not forward.refresh_extrude_profile(p2):
        fail("refresh_extrude_profile declined an N-gon prism")
    r1 = math.hypot(p2["profile"][0][1], p2["profile"][0][2])
    if abs(r1 - 5.0) > 1e-12:
        fail(f"refreshed profile circumradius {r1} != 5.0")
    fitted = {"kind": "EXTRUDE", "height": 1.0, "profile": p["profile"]}
    if forward.refresh_extrude_profile(fitted):
        fail("refresh_extrude_profile must not touch a fitted (no-sides) profile")
    # Revolve ring: rectangular section between the radii, refreshed on edit.
    p = forward.make_params("REVOLVE", DIMS["REVOLVE"], loc)
    if len(p["profile"]) != 4 or any(row[0] != 0.0 for row in p["profile"]):
        fail(f"revolve ring profile should be 4 LINE rows, got {p['profile']}")
    us = [row[1] for row in p["profile"]] + [row[3] for row in p["profile"]]
    if abs(min(us) - 1.0) > 1e-12 or abs(max(us) - 2.0) > 1e-12:
        fail(f"ring radii wrong: {min(us)}..{max(us)}")
    p3 = dict(p, kind="REVOLVE", radius2=3.0)
    if not forward.refresh_revolve_profile(p3):
        fail("refresh_revolve_profile declined a ring")
    us3 = [row[1] for row in p3["profile"]] + [row[3] for row in p3["profile"]]
    if abs(max(us3) - 3.0) > 1e-12:
        fail(f"refreshed ring outer radius {max(us3)} != 3.0")
    fitted_rv = {"kind": "REVOLVE", "profile": p["profile"]}
    if forward.refresh_revolve_profile(fitted_rv):
        fail("refresh_revolve_profile must not touch a fitted profile")
    # Cylinder: base IS the body centre (build/_cylinder spans ±h/2 around it).
    p = forward.make_params("CYLINDER", DIMS["CYLINDER"], loc)
    if tuple(p["base"]) != loc:
        fail(f"cylinder base {p['base']} should equal the drop location")
    print("[ok] placement conventions (cone base offset, cylinder centred)")
    print("ALL FORWARD PARAM TESTS PASSED")


if __name__ == "__main__":
    main()
